### ISSUE TITLE
Cannot estimate Gas

### ISSUE THREAD

**Issue by evmjunkie** [flashbots/searcher-sponsored-tx#20]
Hey guys, I am always getting the error: "Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\": \"2.0\", \"id\": 45, \"error\": {\"code\": -32000, \"message\": \"execution reverted\"}}" Its based on the fact that the RPCs cannot estimate gas on accounts with no ether in it. So I am using this script basically because the wallet contains no ether in it, but on the other side i cannot estimate gas with no ether. What should I do?

**Comment by osas41** [comment]
I’m having the same issue here

**Comment by PaulGG-Code** [comment]
You can check the configuration example here:
https://ethereum.stackexchange.com/questions/122688/how-to-create-and-send-flashbot-bsc/127939#127939

Hope it help!

**Comment by wombatlabs** [comment]
@PaulGG-Code were you able to get it to work on BSC?

**Comment by PaulGG-Code** [comment]
Yes @blockinator I've been able to test it on most EVM's 
Let me know if you need more help

**Comment by Oluwatobilobaoke** [comment]
hello @PaulGG-Code  can you share your successful repo with bsc please.
it's been hell trying to figure it out

**Comment by wombatlabs** [comment]
@PaulGG-Code, this is the error I am getting:
```
Simulation failed, error code: -32000
[2022-05-20T17:07:16.706Z] err: nonce too high: address ADDRESS_SPONSER, tx: 179 state: 0; txhash 0xfe9eb67c62ffadb54d0207bebdd0e3b3f2d21d1ed72429b78661c495ce1cd6f2
[2022-05-20T17:07:16.721Z] (node:19191) UnhandledPromiseRejectionWarning: Error: Failed to simulate response
    at Object.checkSimulation (/PATH_DIRECTORY/searcher-sponsored-tx/src/utils.ts:47:9)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at main (/PATH_DIRECTORY/searcher-sponsored-tx/src/index.ts:104:29)
[2022-05-20T17:07:16.721Z] (node:19191) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[2022-05-20T17:07:16.721Z] (node:19191) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

To fix the `err: nonce too high` I tried resetting MetaMask but that didn't do anything.

**Comment by 12r3r3** [comment]
yes i need help also on this 
\

**Comment by blockinator** [comment]
@PaulGG-Code shoot me a message on Telegram or Discord if you have a chance:
https://t.me/blockinator
Blockinator#2585

**Comment by MataAzi** [comment]
Same problem. "Error: cannot estimate gas; transaction may fail or may require manual gas limit "

**Comment by Sirelor** [comment]
I keep getting NOT INCLUDED IN BLOCK when using the TransferERC20 method. I set PRIORITY_GAS_PRICE to 3000

**Comment by liw92** [comment]
Some error, i've changed gas settings many times, i even set both GWEI.mul to (31) (gas price) and gas price to 150000 (eth gas price was 6gwei)
![image](https://user-images.githubusercontent.com/114318996/192123140-ba6c1927-4e09-47d7-b1c9-42eff516cfb0.png)
![image](https://user-images.githubusercontent.com/114318996/192123147-505abe91-218d-4980-8691-970e5ff506fb.png)
![image](https://user-images.githubusercontent.com/114318996/192123156-2fe4444f-4eab-4852-91c5-d648bf7bd3a7.png)

**Comment by rashtug2** [comment]
> Reference in ne



> Yes @blockinator I've been able to test it on most EVM's Let me know if you need more help

Hello boss, i need help in making it work on other EVM
