### ISSUE TITLE
HELP pls

### ISSUE THREAD

**Issue by lam3r0keiee** [flashbots/searcher-sponsored-tx#36]
Not working long time. Please- tell what my problem[2023-03-12T17:46:56.206Z] C:\Users\Administrator\Desktop\searcher-sponsored-tx-main\node_modules\@ethersproject\logger\src.ts\index.ts:213
        const error: any = new Error(message);
                           ^
[2023-03-12T17:46:56.207Z] Error: bad response (status=400, headers={"date":"Sun, 12 Mar 2023 17:46:56 GMT","content-type":"application/json","content-length":"32","connection":"close","x-amzn-requestid":"34b925c2-1442-4522-a216-d25eb797401a","x-amz-apigw-id":"BrdykG7PCYcF-cg=","vary":"Origin","x-amzn-trace-id":"Root=1-640e1010-243b116c1b0be41e1043538f;Sampled=0"}, body="{\"error\":\"unable to decode txs\"}", requestBody="{\"method\":\"eth_callBundle\",\"params\":[{\"txs\":[\"0xf86d8201a985078eedc5f28252089403567a339b9586e3f0b161f2df6ecdfa43a6921b87063988f836365a801ca0f1b6a34d336d5c080cb5b6a15997d2ca00ce901a336d54a17a051e2ab5954747a0412f16259bb1bb844e8ef52d26e4bc51135c16abf47344ba1a7bb95f7395ab13\",\"0xf8ab82075b85078eedc5f282d2d594795dbf627484f8248d3d6c09c309825c1563e87380b844a9059cbb0000000000000000000000001eba3256bbda2ca07765bd06c33a4efbaa553631000000000000000000000000000000000000000000000000016272cc7e5cfc581ba0ab104947c3f1da75ffd5e85b3b896c6535bf611b21f67a4c647df64eb9209c5ca04a733f0f4b99cfb783c37e1262e70081f8c7bbbe603d5f61e00bf7da790c9df5\"],\"blockNumber\":\"0x1008dd2\",\"stateBlockNumber\":\"latest\"}],\"id\":42,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://relay.flashbots.net", code=SERVER_ERROR, version=web/5.4.0)
    at Logger.makeError (C:\Users\Administrator\Desktop\searcher-sponsored-tx-main\node_modules\@ethersproject\logger\src.ts\index.ts:213:28)
    at Logger.throwError (C:\Users\Administrator\Desktop\searcher-sponsored-tx-main\node_modules\@ethersproject\logger\src.ts\index.ts:225:20)
    at C:\Users\Administrator\Desktop\searcher-sponsored-tx-main\node_modules\@ethersproject\web\src.ts\index.ts:251:24
    at step (C:\Users\Administrator\Desktop\searcher-sponsored-tx-main\node_modules\@ethersproject\web\lib\index.js:33:23)
    at Object.next (C:\Users\Administrator\Desktop\searcher-sponsored-tx-main\node_modules\@ethersproject\web\lib\index.js:14:53)
    at fulfilled (C:\Users\Administrator\Desktop\searcher-sponsored-tx-main\node_modules\@ethersproject\web\lib\index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by lam3r0keiee** [comment]
my TG @musafa_officiall

**Comment by Topxy264** [comment]
I can help you with the fix

**Comment by onlyinpk** [comment]
intresting
